"""
DBML Generator — ERDSchema → Database Markup Language text.

Output is valid DBML consumable by dbdiagram.io and the official
`@dbml/core` parser used in the Monaco editor preview tab.

Ref cardinality notation:
  -   one-to-one
  >   many-to-one  (FK side points at the "one" side)
  <   one-to-many  (inverse of the above)
  <>  many-to-many (via junction table)
"""

from __future__ import annotations

from app.schemas.erd_schema import Column, DataType, ERDSchema, RelationshipType


def _dbml_type(col: Column) -> str:
    """Return a concise DBML type string."""
    dt = col.data_type
    tp = col.type_params or {}

    if dt == DataType.VARCHAR:
        return f"varchar({tp.get('length', 255)})"
    if dt == DataType.CHAR:
        return f"char({tp.get('length', 1)})"
    if dt in (DataType.DECIMAL, DataType.NUMERIC):
        p, s = tp.get("precision", 10), tp.get("scale", 2)
        return f"decimal({p},{s})"
    if dt == DataType.ENUM:
        return col.name + "_type"
    _MAP: dict[DataType, str] = {
        DataType.SMALLINT:   "smallint",
        DataType.INTEGER:    "integer",
        DataType.BIGINT:     "bigint",
        DataType.REAL:       "real",
        DataType.FLOAT:      "float",
        DataType.DOUBLE:     "double",
        DataType.SERIAL:     "serial",
        DataType.BIGSERIAL:  "bigserial",
        DataType.TEXT:       "text",
        DataType.DATE:       "date",
        DataType.TIME:       "time",
        DataType.TIMESTAMP:  "timestamp",
        DataType.TIMESTAMPTZ: "timestamptz",
        DataType.INTERVAL:   "interval",
        DataType.BOOLEAN:    "boolean",
        DataType.BYTEA:      "bytea",
        DataType.BLOB:       "blob",
        DataType.JSON:       "json",
        DataType.JSONB:      "jsonb",
        DataType.UUID:       "uuid",
    }
    return _MAP.get(dt, dt.value.lower())


def generate_dbml(schema: ERDSchema) -> str:
    out: list[str] = ["// Generated by DBDesign Platform"]
    if schema.title:
        out.append(f"// {schema.title}")
    if schema.description:
        out.append(f"// {schema.description}")
    out.append("")

    # ── Enum blocks ───────────────────────────────────────────────────────────
    for e in schema.enums:
        out.append(f"Enum {e.name} {{")
        for v in e.values:
            out.append(f"  {v}")
        out += ["}", ""]

    # ── Table blocks ──────────────────────────────────────────────────────────
    for table in schema.tables:
        out.append(f"Table {table.name} {{")
        if table.comment:
            out.append(f'  Note: "{table.comment}"')

        for col in table.columns:
            settings: list[str] = []
            if col.is_primary_key:
                settings.append("pk")
            if col.is_auto_increment:
                settings.append("increment")
            if col.is_unique and not col.is_primary_key:
                settings.append("unique")
            if not col.is_nullable and not col.is_primary_key:
                settings.append("not null")
            if col.default_value:
                settings.append(f"default: `{col.default_value}`")
            if col.check_constraint:
                settings.append(f"note: 'CHECK: {col.check_constraint}'")
            elif col.comment:
                settings.append(f'note: "{col.comment}"')

            setting_str = f" [{', '.join(settings)}]" if settings else ""
            out.append(f"  {col.name} {_dbml_type(col)}{setting_str}")

        # Inline indexes
        all_idx = [
            *[idx for idx in table.indexes],
        ]
        if all_idx:
            out.append("")
            out.append("  indexes {")
            for idx in all_idx:
                cols = f"({', '.join(idx.columns)})"
                attrs: list[str] = [f"name: '{idx.name}'"]
                if idx.is_unique:
                    attrs.append("unique")
                if idx.index_type.value != "BTREE":
                    attrs.append(f"type: {idx.index_type.value}")
                out.append(f"    {cols} [{', '.join(attrs)}]")
            out.append("  }")

        out += ["}", ""]

    # ── Ref lines ─────────────────────────────────────────────────────────────
    if schema.relationships:
        for rel in schema.relationships:
            if rel.relationship_type == RelationshipType.ONE_TO_ONE:
                arrow = "-"
            elif rel.relationship_type == RelationshipType.MANY_TO_MANY:
                arrow = "<>"
            else:
                # ONE_TO_MANY: from_table is the "many" side (holds the FK)
                arrow = ">"

            line = (
                f"Ref: {rel.from_table}.{rel.from_column} "
                f"{arrow} "
                f"{rel.to_table}.{rel.to_column}"
            )
            if rel.label:
                line += f' [note: "{rel.label}"]'
            out.append(line)
        out.append("")

    return "\n".join(out)
