"""
Prisma Schema Generator — ERDSchema → schema.prisma text.

Emits: datasource, generator, enum blocks, model blocks with
@id, @unique, @default, @relation, @@index, and @db.* directives.
"""

from __future__ import annotations

from app.schemas.erd_schema import (
    Column,
    DataType,
    DBTarget,
    ERDSchema,
    ForeignKey,
)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _pascal(name: str) -> str:
    """snake_case → PascalCase (e.g. order_item → OrderItem)."""
    return "".join(word.capitalize() for word in name.split("_"))


def _prisma_scalar(col: Column) -> str:
    """Map DataType → Prisma scalar type name."""
    _MAP: dict[DataType, str] = {
        DataType.SMALLINT:   "Int",
        DataType.INTEGER:    "Int",
        DataType.BIGINT:     "BigInt",
        DataType.REAL:       "Float",
        DataType.FLOAT:      "Float",
        DataType.DOUBLE:     "Float",
        DataType.DECIMAL:    "Decimal",
        DataType.NUMERIC:    "Decimal",
        DataType.SERIAL:     "Int",
        DataType.BIGSERIAL:  "BigInt",
        DataType.CHAR:       "String",
        DataType.VARCHAR:    "String",
        DataType.TEXT:       "String",
        DataType.DATE:       "DateTime",
        DataType.TIME:       "DateTime",
        DataType.TIMESTAMP:  "DateTime",
        DataType.TIMESTAMPTZ: "DateTime",
        DataType.INTERVAL:   "String",
        DataType.BOOLEAN:    "Boolean",
        DataType.BYTEA:      "Bytes",
        DataType.BLOB:       "Bytes",
        DataType.JSON:       "Json",
        DataType.JSONB:      "Json",
        DataType.UUID:       "String",
        DataType.ENUM:       _pascal(col.name),  # maps to generated enum block
    }
    return _MAP.get(col.data_type, "String")


def _db_directive(col: Column, target: DBTarget) -> str | None:
    """Return a @db.* directive for types that need explicit DB-level mapping."""
    dt = col.data_type
    tp = col.type_params or {}
    if target == DBTarget.POSTGRESQL:
        if dt == DataType.VARCHAR:
            return f"@db.VarChar({tp.get('length', 255)})"
        if dt == DataType.CHAR:
            return f"@db.Char({tp.get('length', 1)})"
        if dt == DataType.DECIMAL:
            return f"@db.Decimal({tp.get('precision', 10)}, {tp.get('scale', 2)})"
        if dt == DataType.NUMERIC:
            return f"@db.Decimal({tp.get('precision', 10)}, {tp.get('scale', 2)})"
        if dt == DataType.SMALLINT:
            return "@db.SmallInt"
        if dt == DataType.BIGINT:
            return "@db.BigInt"
        if dt == DataType.TIMESTAMPTZ:
            return "@db.Timestamptz(6)"
        if dt == DataType.BYTEA:
            return "@db.ByteA"
        if dt == DataType.JSON:
            return "@db.Json"
    elif target == DBTarget.MYSQL:
        if dt == DataType.VARCHAR:
            return f"@db.VarChar({tp.get('length', 255)})"
        if dt in (DataType.TIMESTAMP, DataType.TIMESTAMPTZ):
            return "@db.DateTime(0)"
        if dt == DataType.BOOLEAN:
            return "@db.TinyInt"
    return None


def _default_directive(col: Column) -> str | None:
    """Map common SQL DEFAULT expressions to Prisma @default(…) directives."""
    if col.is_auto_increment or col.data_type in (DataType.SERIAL, DataType.BIGSERIAL):
        return "@default(autoincrement())"
    if col.data_type == DataType.UUID and (
        col.is_primary_key or col.default_value in ("gen_random_uuid()", "uuid_generate_v4()")
    ):
        return "@default(uuid())"
    if col.default_value is None:
        return None
    dv = col.default_value.strip().upper()
    if dv in ("NOW()", "CURRENT_TIMESTAMP"):
        return "@default(now())"
    if dv == "FALSE":
        return "@default(false)"
    if dv == "TRUE":
        return "@default(true)"
    # Fall back to dbgenerated() for arbitrary SQL expressions
    return f'@default(dbgenerated("{col.default_value}"))'


# ── Public entry point ────────────────────────────────────────────────────────


def generate_prisma(schema: ERDSchema) -> str:
    target = schema.db_target
    provider_map = {
        DBTarget.POSTGRESQL: "postgresql",
        DBTarget.MYSQL:      "mysql",
        DBTarget.SQLITE:     "sqlite",
    }
    out: list[str] = ["// Generated by DBDesign Platform", ""]

    # ── datasource ────────────────────────────────────────────────────────────
    out += [
        "datasource db {",
        f'  provider = "{provider_map[target]}"',
        '  url      = env("DATABASE_URL")',
        "}",
        "",
    ]

    # ── generator ─────────────────────────────────────────────────────────────
    out += [
        "generator client {",
        '  provider = "prisma-client-js"',
        "}",
        "",
    ]

    # ── enum blocks ───────────────────────────────────────────────────────────
    for e in schema.enums:
        out.append(f"enum {_pascal(e.name)} {{")
        for v in e.values:
            out.append(f"  {v.upper()}")
        out += ["}", ""]

    # ── model blocks ──────────────────────────────────────────────────────────
    for table in schema.tables:
        # Quick lookup: col_name → ForeignKey (single-col FKs only)
        fk_col_map: dict[str, ForeignKey] = {}
        for fk in table.foreign_keys:
            if len(fk.columns) == 1:
                fk_col_map[fk.columns[0]] = fk

        out.append(f"model {_pascal(table.name)} {{")
        if table.comment:
            out.append(f"  // {table.comment}")

        for col in table.columns:
            scalar   = _prisma_scalar(col)
            nullable = "?" if (col.is_nullable and not col.is_primary_key) else ""
            directives: list[str] = []

            if col.is_primary_key:
                directives.append("@id")

            d = _default_directive(col)
            if d:
                directives.append(d)

            if col.is_unique and not col.is_primary_key:
                directives.append("@unique")

            db = _db_directive(col, target)
            if db:
                directives.append(db)

            directive_str = ("  " + "  ".join(directives)) if directives else ""
            # Align columns with padding (cosmetic)
            out.append(f"  {col.name:<20} {scalar}{nullable}{directive_str}")

        # Relation fields (one per single-column FK)
        for fk in table.foreign_keys:
            if len(fk.columns) == 1:
                ref_model = _pascal(fk.referenced_table)
                fk_col    = fk.columns[0]
                ref_col   = fk.referenced_columns[0]
                field_name = fk.referenced_table  # camelCase relation field
                nullable_q = "?" if any(
                    c.name == fk_col and c.is_nullable
                    for c in table.columns
                ) else ""
                out.append(
                    f"  {field_name:<20} {ref_model}{nullable_q}  "
                    f"@relation(fields: [{fk_col}], references: [{ref_col}])"
                )

        # Composite indexes / unique constraints
        for idx in table.indexes:
            cols = ", ".join(idx.columns)
            if idx.is_unique:
                out.append(f"  @@unique([{cols}])")
            else:
                out.append(f"  @@index([{cols}])")

        if table.comment:
            out.append(f'\n  @@map("{table.name}")')

        out += ["}", ""]

    return "\n".join(out)
